FROM node:18.17.0-alpine AS base

# Stage 1: Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY dist/package*.json ./
RUN npm install --omit=dev
RUN npm install -g sharp

# Stage 2: Create the production image
FROM base AS runner

WORKDIR /app

ENV NODE_ENV production

COPY dist/public ./apps/esp/public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY dist/.next/standalone ./
COPY dist/.next/static ./dist/.next/static

EXPOSE 3000

# https://nextjs.org/docs/messages/sharp-missing-in-production
ENV NEXT_SHARP_PATH=/usr/local/lib/node_modules/sharp
COPY --from=deps --chown=nextjs:nodejs /usr/local/lib/node_modules/sharp /usr/local/lib/node_modules/sharp

ENV PORT 3000

ENV NEXT_TELEMETRY_DISABLED 1

ENV HOSTNAME "0.0.0.0"

CMD ["node", "apps/esp/server.js"]
